#!/bin/sh /etc/rc.common
# whitelist-bypass transparent proxy service

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/wl-joiner
CONFIGFILE=/etc/config/wlbypass

start_service() {
    config_load wlbypass

    local enabled link resources debug_mode lan_iface dns
    config_get_bool enabled main enabled 0
    [ "$enabled" -eq 0 ] && return 0

    config_get link main link ''
    [ -z "$link" ] && {
        logger -t wlbypass "ERROR: no link configured"
        return 1
    }

    config_get resources main resources 'moderate'
    config_get_bool debug_mode main debug 0
    config_get lan_iface main lan_iface 'br-lan'
    config_get dns main dns '1.1.1.1,8.8.8.8'

    local args="--tm-link $link --tun --resources $resources --lan-iface $lan_iface --dns $dns"

    [ "$debug_mode" -eq 1 ] && args="$args --debug"

    procd_open_instance
    procd_set_param command $PROG $args
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param file $CONFIGFILE
    procd_close_instance

    logger -t wlbypass "service started: link=$link resources=$resources"
}

service_triggers() {
    procd_add_reload_trigger "wlbypass"
}
